from tkinter import*
root=Tk()
root.title('Задача29. Вариант №5')
nadp_A = Label(root, text = 'Введите сторону А', font = 'Arial 12')
nadp_B = Label(root, text = 'Введите сторону B', font = 'Arial 12')
nadp_C = Label(root, text = 'Введите сторону C', font = 'Arial 12')
nadp_alpfa= Label(root, text = 'угол a', font = 'Arial 12')
nadp_beta= Label(root, text = 'угол b', font = 'Arial 12')
nadp_gamma= Label(root, text = 'угол y', font = 'Arial 12')
nadp_h= Label(root, text = 'высота', font = 'Arial 12')
nadp_S= Label(root, text = 'Площадь', font = 'Arial 12')
nadp_P= Label(root, text = 'Периметр', font = 'Arial 12')
A=DoubleVar()
vA = Entry(root, width=15, textvariable = A)
B=DoubleVar()
vB = Entry(root, width=15, textvariable = B)
C=DoubleVar()
vC = Entry(root, width=15, textvariable = C)
C=DoubleVar()
v_alpfa = Entry(root, widht=15, textvariable =a)
v_beta = Entry(root, widht=15, textvariable =b)
v_gamma = Entry(root, widht=15, textvariable =y)
         
