import tkinter
from tkinter import*
root=Tk("Окно")
root.title("Заголовок")
root.geometry("500x400+300+200")
nadp=Label(root, text= 'Характеристики шрифта', font='Arial 18')
nadp.pack()
knopka_raschet=Button(root, text='Расчет')
knopka_raschet.pack()
pole=Entry(root, width = 20)
pole.pack()
fl_girn = Checkbutton(root, text= 'Полужирный шрифт', onvalue = 1, offvalue = 0)
fl_girn.pack()
fl_kursiv = Checkbutton(root, text= 'Курсив', onvalue = 1, offvalue = 0)
fl_kursiv.pack()
per1 = Radiobutton(root, text= 'Мужчина', value = 1)
per1.pack()
per2 = Radiobutton(root, text= 'Женщина', value = 2)
per2.pack()
ramka1 = Frame(root, width = 500,height = 100)
ramka1.pack()
ramka1 = Frame(root, width = 500, height = 100, bd)
ramka1.pack()
